spring:
  profiles.active: default
---
server.port: 8081
spring:
  profiles: default
  application:
    name: transaction-store
# H2 properties
## browser url for h2 console - http://localhost:8081/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:transactions
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
#        javax:
#          cache:
#          #missing_cache_strategy: fail # Useful for testing if Hibernate creates a second cache manager
#        cache:
#          use_second_level_cache: true
#          use_query_cache: false
##          region.factory_class: jcache

  # Jackson properties
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# cache properties
  cache:
    type: guava
    guava:
      spec: expireAfterAccess=600s
    cache-names: transactions,rateExchanges

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:itest
    username: sa
    password:
    driverClassName: org.h2.Driver

---
  profiles: cacheDisabled
# Disable cache
  cache.type: none
